[package]
name = "user_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.5.3", features = ["std"] }
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_json = "1.0.140"
uuid = { version = "1.17.0", features = ["serde", "v4"] }
